sudo: false

language: node_js

notifications:
  email: false

node_js:
  - '10.15.0'

install:
  - npm install

jobs:
  include:
    - stage: Test
      name: Unit Test
      script: npm run test
    - name: Code Coverage
      script: npm run codecov
    - stage: Deploy
      name: Deploy Docs
      script: npm run docs:build
      if: branch = master
