sudo: false

language: node_js

notifications:
  email: false

node_js:
  - '10.15.0'

install:
  - npm install

script:
  - npm run ci
  - npm run

after_script:
  - npm run codecov

after_success:
  on:
    branch: master
  - ./deploy.sh
