export default {
  'element-ui': {
    linkage_foo: '',
    linkage_bar: '',
    none: '',
    input: '',
    textarea: '',
    select: 'bar',
    inputNumber: 0,
    radio: 'foo',
    checkbox: 'foo',
    switch: false,
    slider: 0,
    datePicker: '',
    timeSelect: '',
    timePicker: '',
    tree: '',
    rate: null,
    cascader: [],
    upload: '',
    custom: ''
  },
  'iview': {
    linkage_foo: '',
    linkage_bar: '',
    none: '',
    input: '',
    textarea: '',
    select: 'bar',
    inputNumber: 0,
    radio: 'foo',
    checkbox: [ 'foo' ],
    switch: false,
    slider: 0,
    datePicker: '',
    timePicker: '',
    tree: '',
    rate: null,
    cascader: [ 'foo', 'bar' ],
    upload: '',
    custom: ''
  }
};
