export default {
  linkage_foo: '',
  linkage_bar: '',
  none: '',
  input: '',
  textarea: '',
  select: 'bar',
  inputNumber: '',
  radio: 'foo',
  checkbox: 'foo',
  switch: false,
  slider: 0,
  datePicker: '',
  timeSelect: '',
  timePicker: '',
  tree: '',
  rate: null,
  cascader: [],
  upload: '',
  custom: ''
};
